apiVersion: apps/v1
kind: Deployment
metadata:
  name: weight-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weight-dashboard
  template:
    metadata:
      labels:
        app: weight-dashboard
    spec:
      containers:
      - name: weight-dashboard
        image: franchyze923/weight-dashboard:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: withings-api-creds
              key: CLIENT_ID
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: withings-api-creds
              key: CLIENT_SECRET
        volumeMounts:
        - name: tokens-secret
          mountPath: /app/readonly-tokens
        - name: tokens-writable
          mountPath: /app/tokens
      volumes:
      - name: tokens-secret
        secret:
          secretName: weight-dashboard-secret
      - name: tokens-writable
        emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: weight-dashboard
spec:
  type: LoadBalancer
  selector:
    app: weight-dashboard
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000